/**
 * An embeddable "Verified Model" badge.
 *
 * The point is not decoration. A badge is a claim, and a claim that cannot be
 * checked is marketing - so this one is generated by actually re-verifying the
 * stored receipt on every request, and it renders the real verdict, including
 * an unflattering one. A receipt whose signature fails renders a red FAILED
 * badge, and a receipt produced without hardware attestation says "simulated"
 * rather than borrowing credibility it has not earned.
 */
import { NextResponse } from "next/server";
import { verifyEvidence } from "cool-nwc";
import { ensureSchema, sql } from "@/lib/db";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function badge(label: string, message: string, color: string): string {
  const labelWidth = Math.max(62, label.length * 6.6 + 20);
  const messageWidth = Math.max(70, message.length * 6.6 + 20);
  const total = labelWidth + messageWidth;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${total}" height="20" role="img" aria-label="${escapeXml(label)}: ${escapeXml(message)}">
  <linearGradient id="s" x2="0" y2="100%">
    <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
    <stop offset="1" stop-opacity=".1"/>
  </linearGradient>
  <clipPath id="r"><rect width="${total}" height="20" rx="3" fill="#fff"/></clipPath>
  <g clip-path="url(#r)">
    <rect width="${labelWidth}" height="20" fill="#555"/>
    <rect x="${labelWidth}" width="${messageWidth}" height="20" fill="${color}"/>
    <rect width="${total}" height="20" fill="url(#s)"/>
  </g>
  <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="11">
    <text x="${labelWidth / 2}" y="15" fill="#010101" fill-opacity=".3">${escapeXml(label)}</text>
    <text x="${labelWidth / 2}" y="14">${escapeXml(label)}</text>
    <text x="${labelWidth + messageWidth / 2}" y="15" fill="#010101" fill-opacity=".3">${escapeXml(message)}</text>
    <text x="${labelWidth + messageWidth / 2}" y="14">${escapeXml(message)}</text>
  </g>
</svg>`;
}

function svg(body: string) {
  return new NextResponse(body, {
    headers: {
      "content-type": "image/svg+xml; charset=utf-8",
      // Badges must reflect the live verdict, not a cached optimistic one.
      "cache-control": "no-cache, no-store, must-revalidate",
    },
  });
}

export async function GET(
  _request: Request,
  context: { params: Promise<{ recordId: string }> },
) {
  const { recordId } = await context.params;

  const db = sql();
  if (!db) return svg(badge("model receipt", "no log", "#9f9f9f"));

  try {
    await ensureSchema();
    const rows = (await db`
      SELECT model, receipt FROM receipts WHERE record_id = ${recordId} LIMIT 1
    `) as Array<{ model: string | null; receipt: unknown }>;

    if (rows.length === 0) return svg(badge("model receipt", "not found", "#9f9f9f"));

    const verdict = await verifyEvidence(rows[0].receipt as never);
    const model = rows[0].model ?? "model";

    if (!verdict.ok) return svg(badge("model receipt", "FAILED", "#e05d44"));

    // Distinguish a hardware-backed verdict from a simulated one. Both are
    // "verified"; only one of them is evidence about hardware.
    const checks = verdict.checks as unknown as
      | Record<string, { status?: string }>
      | undefined;
    const simulated =
      checks?.attestation?.status === "simulated" || checks?.enclave?.status === "simulated";

    return svg(
      badge(
        `verified: ${model}`.slice(0, 40),
        simulated ? "sealed (simulated TEE)" : "sealed (hardware TEE)",
        simulated ? "#2f81f7" : "#2ea44f",
      ),
    );
  } catch {
    return svg(badge("model receipt", "error", "#9f9f9f"));
  }
}
